// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70DzplHjZWOzRyzXShpnrV7IbC2xFvdE',
    appId: '1:658817121063:android:ce3eaeb2fa77103e9fc702',
    messagingSenderId: '658817121063',
    projectId: 'fcm-push-notifications-flutter',
    databaseURL: 'https://fcm-push-notifications-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-push-notifications-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsFYb76LI5QPMfsqcGB1RgD_1UxZ_AWtE',
    appId: '1:658817121063:ios:3a3d546297782b929fc702',
    messagingSenderId: '658817121063',
    projectId: 'fcm-push-notifications-flutter',
    databaseURL: 'https://fcm-push-notifications-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fcm-push-notifications-flutter.appspot.com',
    iosBundleId: 'com.appxpert.notificationcomplete.notificationComplete',
  );
}
